# -*- mode: org; -*-
#+TITLE: README
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Wed Mar 09 20:10:56 EET 2022>
# Time-stamp: <Последнее обновление -- Thursday May 12 11:32:43 EEST 2022>


Скрипт проверяет папку на наличие в ней файлов ~.mp3~, создаёт для каждого файла
директорию с его именем (без расширения) и перемещает файл в созданную
директорию.

** Подробности

   Приложение на моём телефоне ~Smart AudioBook Player~ для прослушивания
   аудио-книг, что, впрочем, понятно из названия, воспринимает все файлы в
   директории как единую книгу. Это, конечно же, удобно когда все файлы
   представляют одну книгу, но уже не так хорошо, когда они представлют что-либо
   разное.

   Лучше создать для каждого файла директорию и переместить в неё файл. Если
   нужно прослушать массу разрозненных источников, заниматься этим становится
   утомительно.

   Для этого и нужен данный скрипт.

** Нужно будет доработать

   - Вывод сообщений, если нет необходимости создавать директории (~.mp3~
     отсутсвуют);

   - Замена некоторых символов в названиях файлов и директорий - например,
     двоеточие, с остальными ещё поэксперементировать;

   - Файлы я предварительно перекодирую (скачиваю интересные лекции или обзоры в
     ~.mp4~), можно было бы кодировку делать здесь же. Образец взять в скрипте
     ~yoffre.py~;

   - Можно также осуществить перемещение созданных папок в нужное место;
